services:
  reportproc:
    build: 
      context: .
      dockerfile: "./images/dev/Dockerfile"
    volumes:
      - ./src:/report-processor/src
      - ./scrapped_data:/report-processor/scrapped_data
    links: 
      - redis
    develop:
      watch:
        - action: rebuild
          path: ./src/requirements.txt
        - action: rebuild
          path: ./images/dev/Dockerfile
        - action: rebuild
          path: ./images/dev/start.sh
  redis:
    image: "redis/redis-stack"
    expose:
      - 6379
    ports:
      - 8002:8001
  redis_config:
    image: "ghcr.io/resumechat/search_config:latest"
    environment:
      - REDIS_HOST=redis
    links: 
      - redis
      
