services:
  indeedoptimizer:
    image: indeedoptimizer-scraper:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./scrapped_data:/tmp/indeed/scrapped_data
      - ./logs:/tmp/indeed/logs
    environment:
      - DISPLAY
    env_file: ".env"
    links: 
      - redis
  reportproc:
    build: 
      context: .
      dockerfile: "./images/dev/Dockerfile"
    volumes:
      # - ./src:/report-processor/src
      - ./scrapped_data:/report-processor/scrapped_data
    links: 
      - redis
    develop:
      watch:
        - action: sync+restart
          target: /src
          path: ./src
        - action: rebuild
          path: images/dev/*
  redis:
    image: "redis/redis-stack"
    expose:
      - 6379
    ports:
      - 8002:8001
      
